CREATE TABLE FARMER (
farmer_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
full_name VARCHAR(200) NOT NULL,
email VARCHAR(200) NOT NULL UNIQUE,
password_hash VARCHAR(200) NOT NULL,
phone_number VARCHAR(20) NOT NULL,
created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE FARM_PLOT (
plot_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
farmer_id BIGINT NOT NULL,
farm_name VARCHAR(200) NOT NULL,
plot_name VARCHAR(200) NOT NULL,
plot_size DECIMAL(8,2),
latitude DECIMAL(9,6) NOT NULL,
longitude DECIMAL(9,6) NOT NULL,
updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

CONSTRAINT fk_farm_plot_farmer
        FOREIGN KEY (farmer_id)
        REFERENCES farmer(farmer_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);